// Copyright 2023-2024 the Sequoia authors. All rights reserved. MIT license.

export enum ContentType {
    JSON = 'application/json;charset=UTF-8',
    JS = 'application/javascript;charset=UTF-8',
    BINARY = 'application/octet-stream',
    SOAP = 'application/soap+xml;charset=UTF-8',
    ZIP = 'application/zip;charset=UTF-8',
    GZIP = 'application/gzip;charset=UTF-8',
    XML = 'application/xml;charset=UTF-8',
    DOC = 'application/msword;charset=UTF-8',
    AUDIO_MP4 = 'audio/mp4',
    AUDIO_OGG = 'audio/ogg',
    AAC = 'audio/aac',
    AUDIO_MPEG = 'audio/mpeg',
    AUDIO_WEBM = 'audio/webm',
    GIF = 'image/gif',
    JPEG = 'image/jpeg',
    PNG = 'image/png',
    SVG = 'image/svg+xml',
    WEBP = 'image/webp',
    HTTP = 'message/http;charset=UTF-8',
    ENCRYPTED = 'multipart/encrypted;charset=UTF-8',
    FORMDATA = 'multipart/form-data;charset=UTF-8',
    PLAIN = 'text/plain;charset=UTF-8',
    CSS = 'text/css;charset=UTF-8',
    CSV = 'text/csv;charset=UTF-8',
    HTML = 'text/html;charset=UTF-8',
    PHP = 'text/php;charset=UTF-8',
    MARKDOWN = 'text/markdown;charset=UTF-8',
    VIDEO_MPEG = 'video/mpeg',
    VIDEO_MP4 = 'video/mp4',
    VIDEO_OGG = 'video/ogg',
    VIDEO_WEBM = 'video/webm',
    FORM_ENCODED = 'application/x-www-form-urlencoded;charset=UTF-8',
    RAR = 'application/x-rar-compressed',
    TAR = 'application/x-tar',
}
