name: Unit tests & linting

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'README-ru.md'
      - '.gitignore'

permissions:
  contents: read

jobs:
  linting-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.42.4

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

  test-linux:
    runs-on: ubuntu-latest
    needs: linting-formatting

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.42.4

      - name: Run tests
        run: deno task test

  test-windows:
    runs-on: windows-latest
    needs: linting-formatting

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.42.4

      - name: Run tests
        run: deno task test

  test-macos:
    runs-on: macos-latest
    needs: linting-formatting

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.42.4

      - name: Run tests
        run: deno task test
